/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void mainRunsWithoutException() {
        // run main to make sure it doesn't crash
        String[] args = {};
        App.main(args);
    }
}
